language: node_js
sudo: required
node_js:
- '0.10.32'
env:
- NODE_ENV=travis
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: r82VwsMAgvpKa3AUwwJfo4+pDDO8ulj9vp+dEIV/ov/P3j6Uj63XomVB/K/pKCr2fsuT/wWZl6telNk6H+SZ9xLwU1zs5kOBSF8n+yBE/QIP3SBp/aeG/MhPbb2RMaIDGNnq0acalp7QOhPKzEzJvuQrmkuS8ASkXe9sX38f0SSZYZmWdig8CfTS69pJqzCoJBan2LS2QP+D8U+3gPPz1XkLrPTBrJw94V5U8GCZkTNJJ4tuVvPEkOQYtM91X0tuU+UKiSEnuyr21I2DErMd/4kgvqATXA52Dkj4U1k+1dKwI1kjN/QD4ea1K6dI1vmnu8aJwBRWIYDJcwDMM2os9Zlw9mKKp2Yn/qSlokG5DstjJiF0+M2yV8Vb8Q0INQ7XlSG1qvwiLIFqORvWWwMf5KenhWu3pJvKhsTYZWD+imzYsFWOP0IZdE5mXO9js4+dhT4de42D7qIwtivkXvV4SFYjeAwHNk4osYlC8eQif7nXSi7C9COlNwdIHKlV3BaySQI53j76uQt2KRMwuHBl4w5g7PJwumpY3EeDdbyBcMM/Uy3OLjMedNLl6DCFNM4I6YwJC87Sr957eSR9t8N3LYlQd6E0HOh4v3Xx9diWEsuwanemwZ4juxj7dG8U6BdeYFXtkbE39gy61FM5AqVw/97vx72nVV7p6RNEVyg1Doo=
